// TypeShift - Font Library
// Included via <script> in popup.html before popup.js

const typeShiftFonts = {
  sansSerif: [
    "Arial",
    "Helvetica",
    "Verdana",
    "Trebuchet MS",
    "Gill Sans",
    "Noto Sans",
    "Optima",
    "Arial Narrow",
    "Century Gothic",
    "Roboto",
    "Open Sans",
    "Lato",
    "Montserrat",
    "Poppins",
    "Inter",
    "Raleway",
    "Ubuntu",
    "Nunito",
    "Work Sans",
  ],
  serif: [
    "Times New Roman",
    "Georgia",
    "Garamond",
    "Palatino",
    "Baskerville",
    "Playfair Display",
    "Merriweather",
    "PT Serif",
    "Lora",
    "Crimson Text",
    "EB Garamond",
    "Libre Baskerville",
    "Bodoni MT",
    "Arvo",
  ],
  monospace: [
    "Courier",
    "Courier New",
    "Lucida Console",
    "Monaco",
    "Consolas",
    "Inconsolata",
    "Fira Code",
    "Source Code Pro",
    "Roboto Mono",
    "Space Mono",
    "Ubuntu Mono",
    "JetBrains Mono",
    "Fira Mono",
  ],
  handwriting: [
    "Patrick Hand",
    "Comic Sans MS",
    "Brush Script MT",
    "Lucida Handwriting",
    "Caveat",
    "Pacifico",
    "Dancing Script",
    "Satisfy",
    "Great Vibes",
    "Sacramento",
    "Handlee",
    "Amatic SC",
    "Indie Flower",
    "Kalam",
    "Shadows Into Light",
  ],
  display: [
    "Impact",
    "Arial Black",
    "Bebas Neue",
    "Lobster",
    "Righteous",
    "Bangers",
    "Abril Fatface",
    "Cinzel",
    "Alfa Slab One",
    "Fredoka One",
    "Patua One",
    "Oswald",
    "Anton",
  ],
};
